ZOSVTEST ; 4/17/14 2:29P
 D T0^ZOSVGUX
 I $D(^%ZOSF("PROD"))#10 S ZOSFFLAG=0
 E  S ZOSFFLAG=1,^%ZOSF("PROD")=$ZDATE($H,"YYYY-MM-DD 24:60:SS")
 S TMP=$T(ZHOROLOG^%POSIX)
 S XRTL=$S(""'=TMP:TMP,1:"$T(ZHOROLOG^%POSIX) is null"),XRTN=$ZV
 S X=$J D JOBPAR^ZOSVGUX W "Got here 1",!
 ZWR
 K Y
 S X=4 D JOBPAR^ZOSVGUX W "Got here 2",!
 ZWR
 D T1^ZOSVGUX
 ZWR ^%ZRTL
 I ""'=TMP K ^%ZRTL(3,XRTL,+$H,XRTN,$P($$ZHOROLOG^%POSIX,",",2))
 E  K ^%ZRTL(3,XRTL,+$H,$P($H,",",2))
 ZK:ZOSFFLAG ^%ZOSF("PROD")
 Q
